name: Tartelet
options:
  bundleIdPrefix: com.BluDesign
  developmentLanguage: en
configs:
  Debug: debug
  Release: release
targets:
  tart-executor:
    type: tool
    platform: macOS
    sources: [tart-executor]
    postCompileScripts:
    - name: Run SwiftLint
      path: scripts/swiftlint.sh
      basedOnDependencyAnalysis: false
    dependencies:
      - package: EnvironmentSettings
        products: EnvironmentSettings
      - package: FileSystem
        products: [FileSystemData, FileSystemDomain]
      - package: GitHub
        products: [GitHubData, GitHubDomain, WebhookServer]
      - package: Logging
        products: [LoggingData, LoggingDomain]
      - package: Networking
        products: [NetworkingData, NetworkingDomain]
      - package: Shell
        products: [ShellData, ShellDomain]
      - package: SSH
        products: [SSHData, SSHDomain]
      - package: VirtualMachine
        products: [VirtualMachineData, VirtualMachineDomain]
localPackages:
  - Packages/EnvironmentSettings
  - Packages/FileSystem
  - Packages/GitHub
  - Packages/Logging
  - Packages/Networking
  - Packages/SSH
  - Packages/Shell
  - Packages/VirtualMachine
