platform :mac do
  lane :build_tart_executor do
    gym(scheme: 'tart-executor',
        configuration: 'Release',
        include_symbols: true,
        output_name: 'tart-executor',
        output_directory: './fastlane/builds',
        export_method: 'mac-application',
        skip_profile_detection: true,
        skip_codesigning: true
      )
  end
end