name: SwiftLint

on:
  workflow_dispatch:
  pull_request:

jobs:
  swiftlint:
    runs-on: [tartelet, "10.0.2.54:5000/tart/macos-sequoia-xcode:latest", "memory:4096", "cpu:2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run swiftlint
        run: swiftlint --quiet --reporter github-actions-logging
